# Generated by Django 2.1.5 on 2019-02-22 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('tenantsName', models.CharField(max_length=100)),
                ('unitNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('workOrder', models.TextField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='maintenancestaff',
            name='workOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenanceStaff', to='rentalworkorder_app.Tenant'),
        ),
    ]
