# Generated by Django 2.1.5 on 2019-02-22 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalworkorder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingadmin',
            name='tenantsName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuildingAdmin', to='rentalworkorder_app.Tenant'),
        ),
    ]
