# Generated by Django 2.1.5 on 2019-02-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalworkorder_app', '0002_auto_20190222_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('priority', models.BooleanField()),
                ('problemDescription', models.TextField()),
                ('permissionToEnter', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='tenant',
            name='workOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalworkorder_app.WorkOrder'),
        ),
    ]
