# Generated by Django 2.1.5 on 2019-02-28 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalworkorder_app', '0003_auto_20190222_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='workOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='rentalworkorder_app.WorkOrder'),
        ),
    ]
